#!/bin/bash

set +o verbose
set -euo pipefail

# generic environment variables used by Gradle build
export GIT_SHA1=$CIRRUS_CHANGE_IN_REPO
export GITHUB_BASE_BRANCH=${CIRRUS_BASE_BRANCH:-}
export GITHUB_BRANCH=$CIRRUS_BRANCH
export GITHUB_REPO=${CIRRUS_REPO_FULL_NAME}
export PROJECT=${CIRRUS_REPO_NAME}
export PULL_REQUEST=${CIRRUS_PR:-false}
export PULL_REQUEST_SHA=${CIRRUS_BASE_SHA:-}
# used by burgr to identify stages of the pipeline
export PIPELINE_ID=${CIRRUS_BUILD_ID}

export LANG=C.UTF-8

TASK_TYPE=$1
if [[ "$TASK_TYPE" != "BUILD"* ]]; then
  export SONARSOURCE_QA=true
fi

: "${CI_BUILD_NUMBER?missing parameter. See https://xtranet-sonarsource.atlassian.net/wiki/spaces/RE/pages/2992210934}"
BUILD_NUMBER=${CI_BUILD_NUMBER}
BUILD_ID=${CI_BUILD_NUMBER}
echo "BUILD_NUMBER: $BUILD_NUMBER"
export BUILD_NUMBER BUILD_ID

if [[ "${GITHUB_TOKEN:-}" == "ENCRYPTED"* ]]; then
  echo "Unsetting GITHUB_TOKEN"
  unset GITHUB_TOKEN
fi

case $BUILD_ID in
    ''|*[!0-9]*) echo "$BUILD_ID is not a number" && exit 1 ;;
esac
set -o verbose
