#!/bin/bash
set -euo pipefail

BUILD_ID=$1

if ! current_version=$(poetry version -s); then
  echo "Could not get version from Poetry project ('poetry version -s')" >&2
  echo "$current_version"
  exit 1
fi
release_version=${current_version%".dev"*}
# In case of 2 digits, we need to add a '0' as the 3rd digit.
digit_count=$(echo "${release_version//./ }" | wc --words)
if [[ "$digit_count" -lt 3 ]]; then
  release_version="$release_version.0"
fi
if [[ "$digit_count" -gt 3 && $release_version =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
  release_version="${BASH_REMATCH[0]}"
  echo "WARN: version was truncated to $release_version because it had more than 3 digits"
fi
new_version="$release_version.${BUILD_ID}"

echo "Replacing version $current_version with $new_version"
poetry version "$new_version"
export PROJECT_VERSION=$new_version
