# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
default_language_version:
  ruby: 2.7.2
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        args: [--unsafe]  # does not support https://yaml.org/type/merge.html
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7  # frozen: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 192ad822316c3a22fb3d3cc8aa6eafa0b8488360  # frozen: v0.45.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 06e4cc849d03f3a59ca223a4046f4bb5bb2aba6d  # frozen: 0.33.0
    hooks:
      - id: check-github-workflows
      - id: check-renovate
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 32ee411cf36142e6082f10870ae62172ce9af133 # frozen: 35.32.0
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: shellcheck
  - repo: https://github.com/rhysd/actionlint
    rev: 4e683ab8014a63fafa117492a0c6053758e6d593  # frozen: v1.7.3
    hooks:
      - id: actionlint
