---
on:
  pull_request:
  merge_group:
jobs:
  pre-commit:
    name: "pre-commit"
    runs-on: github-ubuntu-latest-s
    steps:
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: 2025.12.13
      - uses: SonarSource/gh-action_pre-commit@0ecedc4e4070444a95f6b6714ddc3ebcdde697c4 # 1.1.0
        with:
          extra-args: >
            --from-ref=origin/${{ github.event.pull_request.base.ref }} --to-ref=${{ github.event.pull_request.head.sha }}

          ignore-failure: ${{ github.event_name == 'merge_group' }}
