---
name: Re-trigger Approvals
on:
  pull_request_review:
    types: [submitted, dismissed]
  workflow_dispatch:
    inputs:
      head_sha:
        description: Head SHA of the pull request to re-trigger approvals for
        required: true
        type: string

jobs:
  re-trigger:
    permissions:
      actions: write
      id-token: write
    uses: SonarSource/ci-github-actions/.github/workflows/re-trigger-approvals.yml@master # dogfood
    with:
      head_sha: ${{ github.event.pull_request.head.sha || inputs.head_sha }}
