name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@9e81903b12dd2512d584b958e895808b284b67d2 # 5.7.0
    with:
      publishToPyPI: ${{ !github.event.release.prerelease }} # Only publish to PyPI for non-prerelease releases
      publishToTestPyPI: ${{ github.event.release.prerelease }}
      skipPythonReleasabilityChecks: true
