---
name: sonar-release
# This workflow is triggered when publishing a new github release
# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: 1

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@feat/jd/BUILD-4567-release-workflow-fix
    with:
      publishToPyPI: true
      publishToTestPyPI: true
