name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@8d4ccba8d0b6485e7d15c896b72d69ca1e513bcc # 5.9.5
    with:
      publishToPyPI: ${{ !github.event.release.prerelease }} # Only publish to PyPI for non-prerelease releases
      publishToTestPyPI: ${{ github.event.release.prerelease }}
      skipPythonReleasabilityChecks: true
      isDummyProject: true
