name: Release
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string
      publishToTestPyPI:
        description: 'Publish to Test PyPI instead of PyPI'
        required: false
        type: boolean
        default: false

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@master # dogfood
    with:
      version: ${{ inputs.version }}
      publishToPyPI: ${{ !inputs.publishToTestPyPI }}
      publishToTestPyPI: ${{ inputs.publishToTestPyPI }}
      skipPythonReleasabilityChecks: true
      isDummyProject: true
