name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@95d8b6f47f87da30655fe7fdaa5c4f319f1220df # 5.13.0
    with:
      publishToPyPI: ${{ !github.event.release.prerelease }} # Only publish to PyPI for non-prerelease releases
      publishToTestPyPI: ${{ github.event.release.prerelease }}
      skipPythonReleasabilityChecks: true
      isDummyProject: true
