name: Unified Dogfooding scans
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: github-ubuntu-latest-s
    name: Build
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: SonarSource/ci-github-actions/build-poetry@master # dogfood
        with:
          run-shadow-scans: true

      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@03e023516511b1c9da325ad104c2290e3b91688c # 1.1.0
        with:
          primary_project_key: "SonarSource_sonar-dummy-python-oss"
          primary_platform: "SQC-EU"
          shadow1_project_key: "SonarSource_sonar-dummy-python-oss"
          shadow1_platform: "Next"
          shadow2_project_key: "SonarSource_sonar-dummy-python-oss"
          shadow2_platform: "SQC-US"
